name = "memo-widget-api"
main = "src/index.ts"
compatibility_date = "2024-06-01"

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "memo-widget-db"
database_id = "e45463fb-b511-41ef-aeb5-2651081794ba"
